[package]
name = "lox"
version = "0.1.0"
authors = ["Declan Kelly <dkelly.home@gmail.com>"]
edition = "2018"

[lib]
name = "lox"
path = "src/lib.rs"

[[bin]]
name = "lox"
path = "src/main.rs"
doc = false
doctest = false

[dependencies]
thiserror = "1.0"
