[package]
name = "yali-cli"
version = "0.1.0"
authors = ["Declan Kelly <dkelly.home@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yali = { path = "../" }
tracing-subscriber = "0.2"
tracing = "0.1"
