[package]
name = "walox-cli"
version = "0.1.0"
authors = ["Declan Kelly <dkelly.home@gmail.com>"]
edition = "2018"

[dependencies]
walox = { path = "../" }
tracing-subscriber = "0.3.16"
tracing = "0.1.37"
argh = "0.1.9"
